### PR TITLE
Update event-broadcasting.md 

### PR DESCRIPTION
**Pull request by rony09**

### CODE REVIEW

**Comment by robertbiswas** [comment]
Thanks Rony vai.

**Comment by howtocode-com-bd** [comment]
@All, We had two consecutive build errors while getting last two merges done. The error was: http://imgur.com/a/5WvIF 

Please check your file names, any special character, or any last changes that might be the cause.

Thanks

**Comment by howtocode-com-bd** [comment]
May be it occurred in this merge: https://github.com/howtocode-com-bd/laravel.howtocode.com.bd/pull/21

gitbook build logs: http://imgur.com/a/bfXCb

**Comment by howtocode-com-bd** [comment]
@sohelamin You are a collaborator of this book in gitbook end. Can you please have a look?

**Comment by robertbiswas** [comment]
Sohel vai, I'm checking it.

**Comment by sohelamin** [comment]
Okay vai please check and let me know if you can't figure out I'm at office now.
Will check later if needed :)

**Comment by robertbiswas** [comment]
Ok. Thanks

**Comment by sohelamin** [comment]
@robertbiswas vai you've still a conflict on blade-template.md
Please don't change anymore.
I think the build error is coming from blade-template.md
I'll take care of it soon:)

**Comment by robertbiswas** [comment]
We can rollback to the good commit there were no important changes.

**Comment by robertbiswas** [comment]
I've checked and you did too. But not issues found till now.

**Comment by sohelamin** [comment]
Okay, also if you can remove the last commit which is causing the error made by @townim-faisal

**Comment by robertbiswas** [comment]
the last good commit was cd5ada65fcbbe601b57f87d89a07f0840cf27563

Do you like to reset. I think that'll be the best

**Comment by sohelamin** [comment]
Okay do it please.

**Comment by robertbiswas** [comment]
Ok

**Comment by sohelamin** [comment]
@nuhil vai I've rolled back to previous commit and still the build isn't working.
It's seems like the issue is coming from gitbook end.
I'm trying to contact with their support via slack to figure it out.

**Comment by robertbiswas** [comment]
And it's looks ok in my local gitbook(using gitbook serve). Sorry Sohel vai, I had to go out urgently and just come back.

**Comment by sohelamin** [comment]
Sorry for what @robertbiswas vai? It's not a problem at all :) 
So for now, we should wait for the reply from gitbook.
I guess they use node for building the book.

**Comment by nuhil** [comment]
@sohelamin @robertbiswas 
There was a problem with the book.json file and it needed to change the config to apply book builder 2.x.x

Thanks for your co-operation though. Now, you can take care of the pending pull requests. Happy Contributing :)

**Comment by robertbiswas** [comment]
Thanks Nuhil vai.

**Comment by sohelamin** [comment]
Thank you @nuhil vaiya to figure out that weird issue :)

**Pull request merged**
